### ISSUE TITLE
Autoconfig causing jupyter notebook to fail to autoload Django models

### ISSUE THREAD

**Issue by nanorepublica** [mikebryant/django-autoconfig#23]
Hi Mike,

I am getting the following whenever I try to use `shell_plus --notebook` all is well when I just use `shell_plus`

```python-traceback
[IPKernelApp] WARNING | Error in loading extension: django_extensions.management.notebook_extension
Check your config files in /home/vagrant/.ipython/profile_default
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/shellapp.py", line 267, in init_extensions
    self.shell.extension_manager.load_extension(ext)
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/extensions.py", line 91, in load_extension
    if self._call_load_ipython_extension(mod):
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/extensions.py", line 138, in _call_load_ipython_extension
    mod.load_ipython_extension(self.shell)
  File "/usr/local/lib/python2.7/dist-packages/django_extensions/management/notebook_extension.py", line 5, in load_ipython_extension
    style=no_style())
  File "/usr/local/lib/python2.7/dist-packages/django_extensions/management/shells.py", line 94, in import_objects
    from django.db.models.loading import get_models, get_apps
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/__init__.py", line 6, in <module>
    from django.db.models.query import Q
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 17, in <module>
    from django.db.models.deletion import Collector
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/deletion.py", line 4, in <module>
    from django.db.models import signals, sql
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/__init__.py", line 4, in <module>
    from django.db.models.sql.subqueries import *
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/subqueries.py", line 12, in <module>
    from django.db.models.sql.query import Query
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 22, in <module>
    from django.db.models.sql import aggregates as base_aggregates_module
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/aggregates.py", line 9, in <module>
    ordinal_aggregate_field = IntegerField()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 116, in __init__
    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'founders.settings' (Is it on sys.path? Is there an import error in the settings file?): Could not import settings 'founders.settings' (Is it on sys.path? Is there an import error in the settings file?): cannot import name models
```

pip freeze is:  (important ones are latest ipython/jupyter & django 1.6.11)

```
aloe==0.0.31
aloe-django==0.0.15
amqp==1.4.7
anyjson==0.3.3
apt-xapian-index==0.44
Babel==2.1.1
backports-abc==0.4
backports.ssl-match-hostname==3.4.0.2
billiard==3.3.0.21
bitly-api==0.3
blessings==1.6
boto==2.36.0
boto3==1.2.2
botocore==1.3.9
celery==3.1.19
certifi==2015.11.20
chardet==2.0.1
Collectfast==0.2.3
command-not-found==0.2.44
configobj==4.7.2
coverage==4.0
cssselect==0.9.1
decorator==4.0.4
dendrite==1.1.3
diff-match-patch==20121119
dj-database-url==0.3.0
Django==1.6.11
django-appconf==1.0.1
django-autoconfig==0.3.3
django-autoslug==1.7.2
django-braces==1.8.1
django-celery==3.1.16
django-celery-with-redis==3.0
django-compressor==1.3
django-crispy-forms==1.4.0
django-donations==0.2.3
django-environ==0.4.0
django-extensions==1.5.9
django-fsm==2.2.0
django-fsm-admin==1.2.2
django-fsm-log==1.2.1
django-ical==1.3
django-import-export==0.2.6
django-jsonfield==0.9.2
django-keen==0.1.3
django-mixins==0.0.10
django-money==0.7.3
django-nose==1.4.2
django-phonenumber-field==1.0.0
django-registration==1.0
django-robots==1.1
django-shortuuidfield==0.1.2
django-simple-history==1.6.3
django-storages==1.1.8
django-taggit==0.17.5
django-timedeltafield==0.7.10
django-updater==0.4.0
django-waffle==0.11
djangorestframework==2.4.4
docopt==0.4.0
docutils==0.12
dogpile.cache==0.5.7
dogpile.core==0.4.1
duedil==0.6.1
ecdsa==0.13
extras==0.0.3
Fabric==1.10.1
functools32==3.2.3.post2
future==0.15.2
futures==2.2.0
fuzzywuzzy==0.8.0
geopy==1.9.1
gherkin3==3.1.2
GnuPGInterface==0.3.2
gunicorn==19.2.0
hitch==0.5.5
honcho==0.6.6
icalendar==3.9.1
ipykernel==4.2.0
ipython==4.0.1
ipython-genutils==0.1.0
ipywidgets==4.1.1
Jinja2==2.8
jmespath==0.9.0
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.1.1
jupyter-console==4.0.3
jupyter-core==4.0.6
keen==0.3.0
kombu==3.0.29
language-selector==0.1
lettuce==0.2.21
linecache2==1.0.0
lxml==2.3.2
mailchimp==2.0.9
mailchimp3==1.0.11
Markdown==2.6.5
MarkupSafe==0.23
mistune==0.7.1
mock==1.0.1
nbconvert==4.1.0
nbformat==4.0.1
newrelic==2.58.2.45
nose==1.3.7
notebook==4.0.6
oauthlib==1.0.3
opbeat==3.1.3
Padding==0.4
paramiko==1.16.0
path.py==8.1.2
pbr==1.8.1
pexpect==4.0.1
phonenumbers==7.1.1
pickleshare==0.5
Pillow==3.0.0
pipetools==0.2.7
pluggy==0.3.1
pretend==1.0.8
psycopg2==2.6.1
ptyprocess==0.5
py==1.4.20
py-moneyed==0.6.0
pycrypto==2.6.1
pycurl==7.19.0
pygal==2.0.11
pygeocoder==1.2.5
Pygments==2.0.2
python-apt===0.8.3ubuntu7
python-dateutil==2.4.2
python-debian===0.1.21ubuntu1
python-Levenshtein==0.12.0
python-linkedin==4.1
python-mimeparse==0.1.4
python-subunit==1.1.0
pytz==2015.7
PyYAML==3.11
pyzmq==15.1.0
qtconsole==4.1.1
redis==2.10.5
repoze.lru==0.6
requests==2.8.1
requests-mock==0.7.0
requests-oauth2==0.2.0
requests-oauthlib==0.3.3
retrying==1.3.3
selenium==2.48.0
sh==1.11
shortuuid==0.4.2
simple-history==1.1
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.9.0
South==1.0.2
splinter==0.7.3
sure==1.2.24
tablib==0.10.0
terminado==0.5
testtools==1.8.0
tornado==4.3
tox==2.1.1
traceback2==1.4.0
traitlets==4.0.0
ufw==0.31.1.post1
unattended-upgrades==0.1
unittest2==1.1.0
virtualenv==13.1.2
Werkzeug==0.10.4
yell==0.3.2
```

When I disable the autoconfig lines at the bottom of my settings.py everything is fine, going to keep investigating but wondered if you might have any ideas? 
The notebook does run it is just the autoloading of Models that is failing. When I try to import a model I get:

```python-traceback
from django.db import models
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-3c9a812bb53d> in <module>()
----> 1 from django.db import models

/usr/local/lib/python2.7/dist-packages/django/db/models/__init__.py in <module>()
      3 from django.core.exceptions import ObjectDoesNotExist, ImproperlyConfigured
      4 from django.db.models.loading import get_apps, get_app_paths, get_app, get_models, get_model, register_models, UnavailableApp
----> 5 from django.db.models.query import Q
      6 from django.db.models.expressions import F
      7 from django.db.models.manager import Manager

/usr/local/lib/python2.7/dist-packages/django/db/models/query.py in <module>()
     15 from django.db.models.query_utils import (Q, select_related_descend,
     16     deferred_class_factory, InvalidQuery)
---> 17 from django.db.models.deletion import Collector
     18 from django.db.models import sql
     19 from django.utils.functional import partition

/usr/local/lib/python2.7/dist-packages/django/db/models/deletion.py in <module>()
      2 
      3 from django.db import connections, transaction, IntegrityError
----> 4 from django.db.models import signals, sql
      5 from django.utils.datastructures import SortedDict
      6 from django.utils import six

ImportError: cannot import name signals
```

**Comment by mikebryant** [comment]
My guess would be, one of your `INSTALLED_APPS` has an `__init__.py` that's causing a `django.db.models` import.
In the noteback case, the traceback seems to indicate it's not doing a setup of the models prior to importing `django.db.models` - so mid-way through that import, it imports settings, runs through autoconfig, and something then tries to import the half loaded `django.db.models`..

A reasonable workaround: find whichever app it is and add it to `AUTOCONFIG_DISABLED_APPS`

The root cause of this is really that we're naively importing apps to find out if `<app>/autoconfig.py` exists. If we could be a bit smarter there and figure it out without needing to do a real import, it would solve a lot of these issues...
I'll have another think about that.

**Comment by nanorepublica** [comment]
Awesome, thanks for the pointer! :smiley:

**Comment by nanorepublica** [comment]
Thanks Mike,

My `AUTOCONFIG_DISABLED_APPS`  list is as follows: 

```python
AUTOCONFIG_DISABLED_APPS = [
    'django_nose',
    'django_fsm',
    'django.contrib.admin',
    'django.contrib.sitemaps',
]
```

I guess what is interesting is that I need to specify the admin again? Also might be worth adding the sitemaps contrib app to this django_autoconfig's autoconfig?

**Comment by mikebryant** [comment]
That is odd..

Can you give the `better-autoconfig-module-detection` branch a try - it removes the `AUTOCONFIG_DISABLED_APPS` thing entirely, and hooks into the python importer at a lower level to try and find the autoconfig module without triggering imports.
(I'll need to do some testing with egg modules and such before I merge it into master though - they'll probably break right now)

+1 on `django.contrib.sitemaps` - I'll make a separate issue

**Comment by nanorepublica** [comment]
Cool! I will give a try tomorrow or Sunday.

On 4 December 2015 at 14:48, Mike Bryant <notifications@github.com> wrote:

> That is odd..
>
> Can you give the better-autoconfig-module-detection branch a try - it
> removes the AUTOCONFIG_DISABLED_APPS thing entirely, and hooks into the
> python importer at a lower level to try and find the autoconfig module
> without triggering imports.
> (I'll need to do some testing with egg modules and such before I merge it
> into master though - they'll probably break right now)
>
> +1 on django.contrib.sitemaps - I'll make a separate issue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mikebryant/django-autoconfig/issues/23#issuecomment-161984320>
> .
>



-- 
Andrew Miller
email: nanorepublica@gmail.com

**Comment by nanorepublica** [comment]
Ok so tomorrow or Sunday ended up being several weeks later... but anyway just tried the branch out and comment out the above list of `AUTOCONFIG_DISABLED_APPS` - shouldn't be used anyway - and everything starts up fine with no exceptions. so I would take as all good provided you are happy with it of course :smiley:!
